## Configuration

dataset:
  train:
    name: custom_30cls
    img_path: /home/users/vnguyen/intern20/DATA/250_imgs_per_class_cluster_IMT/train
    ann_path: /home/users/vnguyen/intern20/ANNO/coco_formatted_dataset_imt.json

  test:
    name:
    img_path:
    ann_path:

data_loader:
  num_workers: 4

output_dir:
  path: /home/users/vnguyen/intern20/OUTPUTS/detec2

model:
  name: retinanet_R_50_FPN_1x
  weight: /home/users/vnguyen/intern20/Pretrained-Weight/dtec2/model_final_f10217.pkl
  roi_heads:
    batch_size_per_image: 128
    num_classes: 28

solver:
  ims_per_batch: 4
  base_lr: 0.00025
  max_iter: 300