## Configuration

dataset:
  train:
    name: custom_v0_Retinanet
    img_path: /home/users/vnguyen/intern20/DATA/CUSTOM/V0/train
    ann_path: /home/users/vnguyen/intern20/DATA/CUSTOM/V0/annotations/instances_train.json

  test:
    name:
    img_path:
    ann_path:

data_loader:
  num_workers: 4

output_dir:
  path: /home/users/vnguyen/intern20/OUTPUTS/retinanet

model:
  name: retinanet_R_50_FPN_1x
  weight: /home/users/vnguyen/intern20/Pretrained-Weight/dtec2/model_final_f10217.pkl
  roi_heads:
    batch_size_per_image: 128
    num_classes: 30

solver:
  ims_per_batch: 8 # 4 GPUs, 2 images per a GPU
  base_lr: 0.001
  max_iter: 100000