_BASE_: "KMEANS.yaml"

OUTPUT:
  DIR: 'out'

SOLVER:
  FEATURE_TYPE: 'ORG'

OUTPUT:
  VERBOSE: False

REGRESSOR:
  TYPE: 'RF'
  FEATURES: 'FR2'
  RF:
    BOOTSTRAP: [True]
    MAX_DEPTH: [7]
    MAX_FEATURES: ['auto']
    MIN_SAMPLES_LEAF: [3]
    MIN_SAMPLES_SPLIT: [4]
    N_ESTIMATORS: [100]