MODEL:
  DEBUG: False
FINE_TUNING:
  STATUS: False
DETECTOR:
  LOAD: False
SOLVER:
  GAMMA: 3
  K: 4
  F_TOP: 0.2
  CORR_TYPE: 'PEARSON'
  FILTERING: False
OUTPUT:
  VERBOSE: True
DATASETS:
  TRAIN_TEST_SPLIT: "process_raw_data/out/train_test_split_rcnn_v1.json"
  GT_USER_EXPOS: "process_raw_data/out/gt_usr_exposure_v1.json"
  VIS_CONCEPTS: "process_raw_data/raw_data/visual_concepts/processed_situations"
  PRE_VIS_CONCEPTS: "privacy_baseline/out/optimal_thres_situs.txt"