MODEL:
  DEBUG: False
  PLOT: False

##
DETECTOR:
  LOAD: False

##
USER_SELECTOR:
  STATE: True
  EPS: 0.2
  KEEP: 0.95

##
SOLVER:
  GAMMA: 0
  K: 15
  F_TOP: 0.2
  FEATURE_TYPE: 'ORG'
  CORR_TYPE: 'PEARSON'
  FILTERING: True
  FILT: 0.0

##
PCA:
  STATE: False
  N_COMPONENTS: 6

##
DATASETS:
  TRAIN_TEST_SPLIT: "process_raw_data/out/train_test_split_rcnn_v1.json"
  GT_USER_EXPOS: "process_raw_data/out/gt_usr_exposure_v1.json"
  VIS_CONCEPTS: "process_raw_data/raw_data/visual_concepts/processed_situations"
  PRE_VIS_CONCEPTS: "privacy_baseline/out/rcnn_optimal_thres_situs.txt"

##
OUTPUT:
  VERBOSE: False