MODEL:
  DEBUG: True
FINE_TUNING:
  STATUS: False
DETECTOR:
  LOAD: False
SOLVER:
  GAMMA: 0.2
  K: 3
  F_TOP: 0.3
  FEATURE_TYPE: 'ORG'
  CORR_TYPE: 'KENDALL'
  FILTERING: False
CLUSTEROR:
  TYPE: 'K_MEANS'
REGRESSOR:
  TYPE: 'RF'
OUTPUT:
  VERBOSE: True
DATASETS:
  TRAIN_TEST_SPLIT: "process_raw_data/out/train_test_split_rcnn_v1.json"
  GT_USER_EXPOS: "process_raw_data/out/gt_usr_exposure_v1.json"
  VIS_CONCEPTS: "process_raw_data/raw_data/visual_concepts/processed_situations"
  PRE_VIS_CONCEPTS: "privacy_baseline/out/optimal_thres_situs.txt"