_BASE_: "Base-RCNN-FPN.yaml"

MODEL:
  ROI_HEADS:
    NUM_CLASSES: 30
  WEIGHTS: '/home/users/vnguyen/intern20/PRETRAINED/dtec2/Faster-rcnn50-3x/R-50.pkl'
  MASK_ON: False
  RESNETS:
    DEPTH: 50

DATASETS:
  TRAIN: ("train_v0_Faster-RCNN",)

DATALOADER:
  NUM_WORKERS: 16

OUTPUT_DIR: '/home/users/vnguyen/intern20/OUTPUTS/faster-rcnn/custom_v0'

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (40000, 50000)
  MAX_ITER: 60000

INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704)