OUTPUT:
  DIR: '/home/nguyen/Documents/intern20/Vis-Priva-Expos/privacy_baseline/tools/test_'

SOLVER:
  CORR_TYPE: 'PEARSON'
  CROSS_VAL: False
  K_FOLDS: 8

FE:
  GAMMA: 1
  K: 4

DATASETS:
  TRAIN_TEST_SPLIT: 'process_raw_data/out/train_test_split_rcnn_v1.json'
  GT_USER_EXPOS: 'process_raw_data/out/gt_usr_exposure_v1.json'
  VIS_CONCEPTS: 'process_raw_data/raw_data/visual_concepts/processed_situations'